### ISSUE TITLE
otl_strategy should be None, "drop" or "replace"

### ISSUE THREAD

**Issue by wa1618i** [orlovk/mlutils#1]
I tried the example in main.py but it raises error:
Traceback (most recent call last):

  File "<ipython-input-16-a6b4db153d06>", line 20, in <module>
    merger1.fit(X=train_data, y=train_label)

  File "build/bdist.linux-x86_64/egg/mlutils/mergers/BaseMerger.py", line 53, in fit
    lr.fit(sub_train_x, sub_train_y, sublevel=sublevel+1)

  File "build/bdist.linux-x86_64/egg/mlutils/regressors/BaseRegressor.py", line 71, in fit
    raise AttributeError('otl_strategy should be None, "drop" or "replace"')

AttributeError: otl_strategy should be None, "drop" or "replace"
otl_strategy should be None, "drop" or "replace"

**Comment by orlovk** [comment]
Hi, @wa1618i .
Thanks for the interest in my project, but I don't recommend using it, it is still in very raw state.
According to your question, yes, it should be None in main.py, I just forgot to change it.
But I've got successfull run after changing to None, could you provide a code that you use?
